[package]
name = "object-rainbow-cdc"
version = "0.0.0-a.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "FastCDC for object-rainbow"

[dependencies]
object-rainbow.workspace = true
object-rainbow-amt = { workspace = true, optional = true }
object-rainbow-point.workspace = true

async-fs = { workspace = true, optional = true }
async-walkdir = { workspace = true, optional = true }
blocking = { workspace = true, optional = true }
fastcdc.workspace = true
futures-util.workspace = true
genawaiter-try-stream.workspace = true
sha2.workspace = true
static_assertions.workspace = true

[features]
amt = ["dep:object-rainbow-amt"]
fs = ["dep:async-fs", "dep:blocking"]
walkdir = ["amt", "fs", "dep:async-walkdir"]

[dev-dependencies]
rand.workspace = true
smol.workspace = true

[[example]]
name = "file"
required-features = ["fs"]
