[package]
name = "object-rainbow-axum"
version = "0.0.0-a.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "object-rainbow extractor/response for axum"

[dependencies]
object-rainbow.workspace = true

axum.workspace = true
