[package]
name = "object-rainbow-lamport-signature"
version = "0.0.0-a.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
object-rainbow.workspace = true

bitvec.workspace = true
rand = { workspace = true, optional = true }

[features]
generate = ["dep:rand"]

[dev-dependencies]
smol.workspace = true

[package.metadata.tagit]
skip = true
