[package]
name = "object-rainbow-bridge"
version = "0.0.0-a.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "sending objects over network"

[dependencies]
object-rainbow.workspace = true
object-rainbow-point.workspace = true

async-executor.workspace = true
flume.workspace = true
futures-channel.workspace = true
futures-util = { workspace = true, features = ["sink"] }
genawaiter-try-stream.workspace = true

[dev-dependencies]
smol.workspace = true
